spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: cheng
    password: zy159357+
    url: jdbc:mysql://www.chengix.com:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell
